# Generated by Django 4.1.3 on 2022-11-21 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('personable_type', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=200)),
                ('admin', models.BooleanField(default=False)),
                ('owner', models.BooleanField(default=False)),
                ('time_zone', models.CharField(max_length=15)),
                ('avatar_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.project')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('notify', models.BooleanField(default=True)),
                ('due_on', models.DateField()),
                ('starts_on', models.DateField()),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.todolist')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.people')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.project')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=300)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.project')),
            ],
        ),
    ]
